//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumHelloWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentOwner { get; set; }
        public string CommentContent { get; set; }
        public string CommentDateTime { get; set; }
        public string CommentLikesCount { get; set; }
        public string CommentShareCount { get; set; }
        public string PostLink { get; set; }
    }
}
