//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumHelloWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyRole
    {
        public int RoleID { get; set; }
        public string FacebookID1 { get; set; }
        public string FacebookID2 { get; set; }
        public string Role { get; set; }
    }
}
