//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumHelloWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class People_test
    {
        public int PeopleId { get; set; }
        public string FacebookId { get; set; }
        public string FacebookName { get; set; }
        public string Skills { get; set; }
        public string Phone { get; set; }
        public string AddressName { get; set; }
        public string AddressMapLink { get; set; }
        public string Screennames { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string Gender { get; set; }
        public string InterestedIn { get; set; }
        public string Languages { get; set; }
        public string ReligousViews { get; set; }
        public string ReligousViewsLink { get; set; }
        public string PoliticalViews { get; set; }
        public string PoliticalViewsLink { get; set; }
        public string Relationship { get; set; }
        public string CommentOwner { get; set; }
    }
}
