//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumHelloWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleWorkEdu
    {
        public int ID { get; set; }
        public string FacebookID { get; set; }
        public string Link { get; set; }
        public string Level { get; set; }
        public string DateTime { get; set; }
        public string Role { get; set; }
    }
}
