//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumHelloWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PeopleId { get; set; }
        public string FacebookId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string FacebookLink { get; set; }
        public string Birthday { get; set; }
        public string Gender { get; set; }
        public string InterestedIn { get; set; }
        public string languages { get; set; }
        public string ReligousViews { get; set; }
        public string NickName { get; set; }
        public string Relationship { get; set; }
        public string FavoriteQoutes { get; set; }
    }
}
